package com.katallo.domain.enums;

public enum ErrorCode {
    STORE_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    IMAGE_NOT_FOUND,
    INVITE_NOT_FOUND,
    USER_NOT_FOUND,

    ACCESS_DENIED,
    OWNER_REQUIRED,
    ADMIN_REQUIRED,
    UNAUTHORIZED,
    INVALID_TOKEN,
    TOKEN_EXPIRED,

    RESOURCE_NOT_IN_STORE,
    INVALID_INVITE,
    INVALID_OPERATION,
    VALIDATION_ERROR,

    IMAGE_LIMIT_REACHED,
    UPLOAD_FAILED,

    INTERNAL_SERVER_ERROR
}